### ISSUE TITLE
Console PS4 Compiling

### ISSUE THREAD

**Issue by AndaleObe** [paulov-t/FrostbiteModdingTool#102]
I downloaded Visual Studio 2022. I wanted to try playing with the tool a little. I loaded the project according to the instructions. everything works wonderfully. I wanted to look at the error when compiling NHL 23 PS4. can someone help write the compiler?
![1](https://github.com/paulov-t/FrostbiteModdingTool/assets/53269821/2e169dde-09d1-4231-9ef9-e89f10ba3150)
![2](https://github.com/paulov-t/FrostbiteModdingTool/assets/53269821/50f97896-7be7-49fa-9754-d08818c6de0d)

**Comment by AndaleObe** [comment]
I have inserted all compilers into the NHL 22 PS4 plugin but unfortunately none of them work. I think you have to write a code. Unfortunately I'm not familiar with that. hope @paulov-t  you can help.

**Comment by AndaleObe** [comment]
Is it possible that the “compile game” function generally doesn’t work yet? If I set cant launch mods to true in the profile and use the compiler from FC24, it writes all the data to a ModData folder, only the original data. He cancels the modded ones, which is clear anyway because they don't fit together. What I actually want to say is that when I use whatever game and the "compile game" function, I get the same error message as in the first picture above. could it be that he can't find the path for build moddata?

**Comment by AndaleObe** [comment]
It's a shame no one can help :(

**Comment by AndaleObe** [comment]
do you have to compile yourself? The wiki says "you need to compile" would there be instructions perhaps?

**Comment by AndaleObe** [comment]
![20231228_150045](https://github.com/paulov-t/FrostbiteModdingTool/assets/53269821/e9b7a65d-0ba5-44d3-b31b-6e325819938e)

**Comment by AndaleObe** [comment]
@paulov-t 
hey paul,
I found a way to compile PS4. I copied the Madden 23 compiler into the NHL 23 compiler. it writes all data into a moddata folder. everything works perfectly. I imported a jersey into FMT and the jersey then looks like it does in FMT. I imported a jersey .dds which then converts into PS4 swizzle. But I think if there was a one-to-one import, i.e. dds to dds, it should work in the game. can you just help me with the code for the nhl23ps4textureimporter that makes it a 1:1 swap? please :)

**Comment by AndaleObe** [comment]
Maybe you can use the same format for the importer as when loading the jersey from the ebx.
![Unbenannt](https://github.com/paulov-t/FrostbiteModdingTool/assets/53269821/9031b350-a996-4764-a042-b73a3efceb1e)

**Comment by AndaleObe** [comment]
This is what it looks like when I import the jersey and this is exactly how it looks in the game too.
![1](https://github.com/paulov-t/FrostbiteModdingTool/assets/53269821/0473c02f-815a-4dc7-92f6-6eb101e6e28e)

**Comment by TylerQuint** [comment]
> This is what it looks like when I import the jersey and this is exactly how it looks in the game too. ![1](https://private-user-images.githubusercontent.com/53269821/293247845-0473c02f-815a-4dc7-92f6-6eb101e6e28e.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MjY1MDEsIm5iZiI6MTcwMzgyNjIwMSwicGF0aCI6Ii81MzI2OTgyMS8yOTMyNDc4NDUtMDQ3M2MwMmYtODE1YS00ZGM3LTkyZjYtNmViMTAxZTZlMjhlLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA1MDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYjZlOTk0YjI5NmVhMTE0YjUyNWJhZmM0NjhlNzk1YWJlYzY1OTc0YjM2ODcyMTgzM2M3Y2JmMmEzYTA2NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DLU6p087-VDjn7V0RN4YfjbBzghLqSgvxMyxNSTXRIg)

Try to use fallout 4 texture converter it converts dds to ps4 format and u can inject the converted ones it works on most of the games

**Comment by AndaleObe** [comment]
Unfortunately it doesn't work either. This is what it looks like in the game. I would have to get the file I'm importing to look the way it originally appears when loading.
![grafik](https://github.com/paulov-t/FrostbiteModdingTool/assets/53269821/9596d6ad-769d-485e-bf8d-bcfd957a0a91)

**Comment by AndaleObe** [comment]
I have it. But it is a manual intervention in the dds file. I converted the dds to gnf and then swapped the header to dxt1 in the hex edit - replaced it. and this is what it looks like.
![grafik](https://github.com/paulov-t/FrostbiteModdingTool/assets/53269821/faf55c5b-3eb0-4de0-9c5f-c03103a79705)

**Comment by AndaleObe** [comment]
Now you just have to write the code in the nhl22ps4textureimporter so that it replaces the gnf header with the dds dxt1 header. but I don't have the knowledge for that. maybe can @paulov-t  help?

**Comment by TylerQuint** [comment]
> Now you just have to write the code in the nhl22ps4textureimporter so that it replaces the gnf header with the dds dxt1 header. but I don't have the knowledge for that. maybe can @paulov-t help?

so gnf header worked?cool yeah maybe he needs to do that

**Comment by AndaleObe** [comment]
yes, but the gnf header must then be replaced again by the dxt1. The strange thing is, just a dds with dxt1 doesn't work. you first have to convert a dds dtx1 to gnf and then replace the gnf header with the dds dxt1 header.

**Comment by TylerQuint** [comment]
> yes, but the gnf header must then be replaced again by the dxt1. The strange thing is, just a dds with dxt1 doesn't work. you first have to convert a dds dtx1 to gnf and then replace the gnf header with the dds dxt1 header.

same thing for most of the ps4 games markus recently made a texture converter tool for ue4 which changes header too but the tool is buggy and it doesnt convert really well .And btw when u made modded pkg did all the textures messed up or only the mod u injected?

**Comment by AndaleObe** [comment]
what do you mean the textures are mixed up?

**Comment by TylerQuint** [comment]
> what do you mean the textures are mixed up?

i meant messed up did all the textures messed up or only The texture u injected

**Comment by AndaleObe** [comment]
![20231229_082024](https://github.com/paulov-t/FrostbiteModdingTool/assets/53269821/f2ddd1db-3c34-45f2-879a-026feb8a9ee4)

**Comment by AndaleObe** [comment]
OK, it doesn't seem to work completely in the game yet

**Comment by TylerQuint** [comment]
> by the dxt1. The strange thing is, just a dds with dxt1 doesn'

but its better now right? and does the non modded textures working well?

**Comment by AndaleObe** [comment]
The unmodified textures remain as original.

**Comment by TylerQuint** [comment]
> The unmodified textures remain as original.

cool then i am gonna try fc 24 and how do i make it compile like u did?

**Comment by AndaleObe** [comment]
do you have visual studio?

**Comment by TylerQuint** [comment]
> do you have visual studio?

yes u in discord or telegram?

**Comment by TylerQuint** [comment]
> do you have visual studio?

msg me on this bro i am waiting

**Comment by AndaleObe** [comment]
I first have to see how I can manage the textures. then I will send you the compiler which you simply insert

**Comment by TylerQuint** [comment]
> I first have to see how I can manage the textures. then I will send you the compiler which you simply insert

if u send me the compiler i will be experimenting some things which may even help u bro

**Comment by AndaleObe** [comment]
[AssetCompilerMadden23.zip](https://github.com/paulov-t/FrostbiteModdingTool/files/13791773/AssetCompilerMadden23.zip)

**Comment by TylerQuint** [comment]
> [AssetCompilerMadden23.zip](https://github.com/paulov-t/FrostbiteModdingTool/files/13791773/AssetCompilerMadden23.zip)

thx bro where should i place this
in order to mod fc 24

**Comment by TylerQuint** [comment]
[ddstognf.zip](https://github.com/paulov-t/FrostbiteModdingTool/files/13791824/ddstognf.zip)
u can use this python script to convert dds to gnf just place all the textures inside a folder along with the script it bulks convert

**Comment by AndaleObe** [comment]
you put it under the plugin fc24 and in the profile of fc24 switch I assume you modify, "CanUseModData": true,
"ForceUseModData": true,
"CanLaunchMods": true,

Then when you have modified, you go to launch game and it writes the files to a moddata folder, but then you get an error message that you cannot start the game, which is normal because it is not a PC game. Then you move your data or patch folder and replace it with the one you exported from the pkg and generate a pkg normally as you always do.

**Comment by TylerQuint** [comment]
> you put it under the plugin fc24 and in the profile of fc24 switch I assume you modify, "CanUseModData": true, "ForceUseModData": true, "CanLaunchMods": true, "AssetCompiler": "AssetCompilerMadden23",
> 
> Then when you have modified, you go to launch game and it writes the files to a moddata folder, but then you get an error message that you cannot start the game, which is normal because it is not a PC game. Then you move your data or patch folder and replace it with the one you exported from the pkg and generate a pkg normally as you always do.

thx bro will try something

**Comment by dapple2** [comment]
> you put it under the plugin fc24 and in the profile of fc24 switch I assume you modify, "CanUseModData": true, "ForceUseModData": true, "CanLaunchMods": true, "AssetCompiler": "AssetCompilerMadden23",
> 
> Then when you have modified, you go to launch game and it writes the files to a moddata folder, but then you get an error message that you cannot start the game, which is normal because it is not a PC game. Then you move your data or patch folder and replace it with the one you exported from the pkg and generate a pkg normally as you always do.

Hi bro,Thanks for your tools,Could you explain in detail which path AssetCompilerMadden23.cs is placed in, thanks.

**Comment by dapple2** [comment]
I have a error,     Error when trying to compile mod and launch game. Message: One or more errors occurred. (Could not find class AssetCompilerMadden23 in any plugin! Remember this is case sensitive!!)

**Comment by AndaleObe** [comment]
You have to put it in the plugin folder for the game you want to modify. But I don't know whether the compiler is suitable for FC24 switch. I only tested it for NHL 23.

**Comment by AndaleObe** [comment]
@paulov-t 
I think you might need this data to convert the image accordingly?
[Data.zip](https://github.com/paulov-t/FrostbiteModdingTool/files/13792387/Data.zip)

**Comment by AndaleObe** [comment]
I've tested everything now. The GNF is transparent then in the game. Apparently only this format works but it would have to be displayed correctly
![Uploading 293247845-0473c02f-815a-4dc7-92f6-6eb101e6e28e.png…]()

**Comment by AndaleObe** [comment]
Does anyone know why no legacy files are loaded on NHL 23 PS4?

**Comment by AndaleObe** [comment]
> [ddstognf.zip](https://github.com/paulov-t/FrostbiteModdingTool/files/13791824/ddstognf.zip) u can use this python script to convert dds to gnf just place all the textures inside a folder along with the script it bulks convert

hey bro,

the converter is cool. Can you tell me how I can write a command that finally sets a header "DDS DXT1"

**Comment by AndaleObe** [comment]
I noticed that the "player pants" textures also appear on other teams that I have modified. Many have the same pants although I have modified others. maybe it's the compiler's fault. no idea

**Comment by TylerQuint** [comment]
> > [ddstognf.zip](https://github.com/paulov-t/FrostbiteModdingTool/files/13791824/ddstognf.zip) u can use this python script to convert dds to gnf just place all the textures inside a folder along with the script it bulks convert
> 
> hey bro,
> 
> the converter is cool. Can you tell me how I can write a command that finally sets a header "DDS DXT1"
> 
> The script removes the bytes "header gnf" which also works, but I would then have to add a dds dxt1 header again

I will try to make a script on that bro if it works i will share you

**Comment by TylerQuint** [comment]
> I noticed that the "player pants" textures also appear on other teams that I have modified. Many have the same pants although I have modified others. maybe it's the compiler's fault. no idea I hope @paulov-t they continue to work on the console textures and the right compiler. I support him on ko-fi so he loses motivation, but it's been almost 2 month since he did anything for console :(

Hope he continues what he does

**Comment by AndaleObe** [comment]
I tested a little. NHL 22 and NHL 23 both have problems with modifying pants. The jerseys and socks all work. Some pants work to modify but a few then use the pants from another team that I modified. There may be an incorrect chunkID assignment when compiling. does anyone else have this problem?

**Comment by AndaleObe** [comment]
@paulov-t 
What do you actually have to do to get functionality like FC24 or other games, console games (NHL 23). legacy files, meshes etc. or is this due to the SDK as it cannot be fully started (Windows)

**Comment by dapple2** [comment]
> You have to put it in the plugin folder for the game you want to modify in visual studio 2022. But I don't know whether the compiler is suitable for FC24 switch. I only tested it for NHL 23.

I have installed visual studio 2022. I have a question. Should AssetCompilerMadden23.cs be placed in the switch FC24 plugin folder or the visual studio 2022 plug-in plugin folder? Thanks.

**Comment by AndaleObe** [comment]
but you could ask @TylerQuint  if the whole thing works for fc24 ps4

**Comment by dapple2** [comment]
You can move the .cs into the fc24 switch plug in folder in visual studio under plug ins madden23

I don't understand this sentence,There is no plug-in folder in my visual studio directory.Thanks.
![image](https://github.com/paulov-t/FrostbiteModdingTool/assets/44426541/93a5b410-b3b8-4934-9536-345e0f983561)

**Comment by AndaleObe** [comment]
> You can move the .cs into the fc24 switch plug in folder in visual studio under plug ins madden23
> 
> I don't understand this sentence,There is no plug-in folder in my visual studio directory.Thanks. ![image](https://private-user-images.githubusercontent.com/44426541/294833248-93a5b410-b3b8-4934-9536-345e0f983561.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTkxMDUsIm5iZiI6MTcwNDY5ODgwNSwicGF0aCI6Ii80NDQyNjU0MS8yOTQ4MzMyNDgtOTNhNWI0MTAtYjNiOC00OTM0LTk1MzYtMzQ1ZTBmOTgzNTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA3MjY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMGVmNjNiNTM4YzRiNzdjNTMxYjVlZTJlNzJhMTY3YWE4ODNiZDgwZWExNTdmZmNiZmVlMTdiN2UxZjI0OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c6iBe7gXhIIUwzrsXbQJCZwv09G4bkP3aqoSiwcgjxA)

you have to load the project FMT in visual studio. On the FMT Code under Compiling and Debugging, you have instructions from @paulov-t

**Comment by TylerQuint** [comment]
> but you could ask @TylerQuint if the whole thing works for fc24 ps4

Fc 24's compiler is  working for fc 24 so no need other compilers but the moddata generates full game and patch so we need to create full game fpkg it is so much time consuming need to test mod sometime

**Comment by AndaleObe** [comment]
> > but you could ask @TylerQuint if the whole thing works for fc24 ps4
> 
> Fc 24's compiler is working for fc 24 so no need other compilers but the moddata generates full game and patch so we need to create full game fpkg it is so much time consuming need to test mod sometime

yes, that's exactly how it is with NHL 23. Everything is always loaded into the moddata folder and finally it modifies the .cas and .toc

**Comment by AndaleObe** [comment]
@TylerQuint 
Please let me know whether the textures that you have modified also appear on another team even though you have modified a different texture there.

**Comment by TylerQuint** [comment]
> @TylerQuint Please let me know whether the textures that you have modified also appear on another team even though you have modified a different texture there.

will tell u when i test that bro but idk when i can test i dont have enough space to make fpkg file  after compiling and i have a weak lap too

**Comment by AndaleObe** [comment]
> > @TylerQuint Please let me know whether the textures that you have modified also appear on another team even though you have modified a different texture there.
> 
> will tell u when i test that bro but idk when i can test i dont have enough space to make fpkg file after compiling and i have a weak lap too

ok bro,
no stress. Once you've tested it, just let us know

**Comment by dapple2** [comment]
> > You can move the .cs into the fc24 switch plug in folder in visual studio under plug ins madden23
> > I don't understand this sentence,There is no plug-in folder in my visual studio directory.Thanks. ![image](https://private-user-images.githubusercontent.com/44426541/294833248-93a5b410-b3b8-4934-9536-345e0f983561.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTkxMDUsIm5iZiI6MTcwNDY5ODgwNSwicGF0aCI6Ii80NDQyNjU0MS8yOTQ4MzMyNDgtOTNhNWI0MTAtYjNiOC00OTM0LTk1MzYtMzQ1ZTBmOTgzNTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA3MjY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMGVmNjNiNTM4YzRiNzdjNTMxYjVlZTJlNzJhMTY3YWE4ODNiZDgwZWExNTdmZmNiZmVlMTdiN2UxZjI0OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c6iBe7gXhIIUwzrsXbQJCZwv09G4bkP3aqoSiwcgjxA)
> 
> you have to load the project FMT in visual studio. On the FMT Code under Compiling and Debugging, you have instructions from @paulov-t
> 
> .NET 7.+ is required Open the FrostbiteModdingUI.sln using Visual Studio 2022 (Community edition is fine) Right click FrostbiteModdingUI project and select "Set as Startup Project" Press F5 to Debug

I have successfully used vc2022 to load FrostbiteModdingUI.sln. I also followed your instructions and modified the FC24SwitchProfile.json file. Pressing F5 can also run successfully, but it prompts that AssetCompilerMadden23.cs is missing. I don’t know where this file is placed.

![image](https://github.com/paulov-t/FrostbiteModdingTool/assets/44426541/9c519c6a-e0a4-40a2-8bac-b2078f01e4d7)
![image](https://github.com/paulov-t/FrostbiteModdingTool/assets/44426541/34ceb59f-d8bb-4e0e-af1f-84d8a392a403)
![image](https://github.com/paulov-t/FrostbiteModdingTool/assets/44426541/d6a0f9ab-e0e3-4dfd-868b-5140e5320e5d)

**Comment by AndaleObe** [comment]
> > > You can move the .cs into the fc24 switch plug in folder in visual studio under plug ins madden23
> > > I don't understand this sentence,There is no plug-in folder in my visual studio directory.Thanks. ![image](https://private-user-images.githubusercontent.com/44426541/294833248-93a5b410-b3b8-4934-9536-345e0f983561.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTkxMDUsIm5iZiI6MTcwNDY5ODgwNSwicGF0aCI6Ii80NDQyNjU0MS8yOTQ4MzMyNDgtOTNhNWI0MTAtYjNiOC00OTM0LTk1MzYtMzQ1ZTBmOTgzNTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA3MjY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMGVmNjNiNTM4YzRiNzdjNTMxYjVlZTJlNzJhMTY3YWE4ODNiZDgwZWExNTdmZmNiZmVlMTdiN2UxZjI0OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c6iBe7gXhIIUwzrsXbQJCZwv09G4bkP3aqoSiwcgjxA)
> > 
> > 
> > you have to load the project FMT in visual studio. On the FMT Code under Compiling and Debugging, you have instructions from @paulov-t
> > .NET 7.+ is required Open the FrostbiteModdingUI.sln using Visual Studio 2022 (Community edition is fine) Right click FrostbiteModdingUI project and select "Set as Startup Project" Press F5 to Debug
> 
> I have successfully used vc2022 to load FrostbiteModdingUI.sln. I also followed your instructions and modified the FC24SwitchProfile.json file. Pressing F5 can also run successfully, but it prompts that AssetCompilerMadden23.cs is missing. I don’t know where this file is placed.
> 
> ![image](https://private-user-images.githubusercontent.com/44426541/294842638-9c519c6a-e0a4-40a2-8bac-b2078f01e4d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDIxODksIm5iZiI6MTcwNDcwMTg4OSwicGF0aCI6Ii80NDQyNjU0MS8yOTQ4NDI2MzgtOWM1MTljNmEtZTBhNC00MGEyLThiYWMtYjIwNzhmMDFlNGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA4MTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkN2M5YTAwNmUxNTRkZjBmN2Y2ODVkMjIzMGYxYzQ1YzM0NTBlM2FjNDVmOGJmZmZhMGI1MDhmNjkzZDE0ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dfak-By86EMjPiRjByXDy9AHQEFi5Q_-RGvDCA30svk) ![image](https://private-user-images.githubusercontent.com/44426541/294842685-34ceb59f-d8bb-4e0e-af1f-84d8a392a403.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDIxODksIm5iZiI6MTcwNDcwMTg4OSwicGF0aCI6Ii80NDQyNjU0MS8yOTQ4NDI2ODUtMzRjZWI1OWYtZDhiYi00ZTBlLWFmMWYtODRkOGEzOTJhNDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA4MTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YjlhYzJlNjA4ODBlYTQ2NzM0NWM3OGI3MDdkNjE5MWViMDg1ZjU3YTY1NThkZmEwNTQ4NTVlZTkwOTA0MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EOZQQ3ii0KQfjjNAv1sVCBRujZeUGVFH3mNbM4IfLYo) ![image](https://private-user-images.githubusercontent.com/44426541/294842746-d6a0f9ab-e0e3-4dfd-868b-5140e5320e5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDIxODksIm5iZiI6MTcwNDcwMTg4OSwicGF0aCI6Ii80NDQyNjU0MS8yOTQ4NDI3NDYtZDZhMGY5YWItZTBlMy00ZGZkLTg2OGItNTE0MGU1MzIwZTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA4MTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZDFlNjU3NmQ4YTQ2NGQyMjZlYTUzZmFhMjUyZWI3OWQ5OTMyZGUwZWY0YjkxMjFkYWFlZDMwZDA5OGY1ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KjoDayeIDeRBtA0g4ScGsauIJSvoOxrPaM1zUICECGc)

you don't have to use the madden compiler. you can leave everything as it is. Only in the FC24 switch profile for forcemoddata and can launch mods do you have to enter true instead of false

**Comment by dapple2** [comment]
I'm confused now. I don't know how the file AssetCompilerMadden23.cs is related to switch fc24. I'm failing at this last step.Thanks.

**Comment by AndaleObe** [comment]
I don't think the community is that small when it comes to modding EAFC24 etc for PS4. There are also people in the soccergaming forum who ask about it :)
and @paulov-t has made it possible to load and modify PS4 console games on the Frostbite engine.

**Comment by AndaleObe** [comment]
> I'm confused now. I don't know how to associate AssetCompilerMadden23.cs with switch fc24. I'm failing at this last step.

You don't have to do anything, leave the FC24 compiler inside. Apparently only NHL 23 requires the Madden compiler. Leave everything as it is originally, just set the two entries in the profile to true

**Comment by AndaleObe** [comment]
> > > > I'm confused now. I don't know how to associate AssetCompilerMadden23.cs with switch fc24. I'm failing at this last step.
> > > 
> > > 
> > > You don't have to do anything, leave the FC24 compiler inside. Apparently only NHL 23 requires the Madden compiler. Leave everything as it is originally, just set the two entries in the profile to true
> > 
> > 
> > Ok,Thanks,I have successfully run the mod, but I found that there is a problem with the kit texture loaded by fmt.This should be because FMT cannot load the switch fc24 texture correctly.
> 
> Try this https://github.com/paulov-t/FrostbiteModdingTool/files/13791824/ddstognf.zip

@paulov-t describes that there are problems in the image viewer. as everything regarding console textures is still a work in progress.

**Comment by TylerQuint** [comment]
@AndaleObe i applied a face mod using mod loader and compiled the game the miniface worked in game but the face mod didn't work but the default face appeared

**Comment by AndaleObe** [comment]
> @AndaleObe i applied a face mod using mod loader and compiled the game the miniface worked in game but the face mod didn't work but the default face appeared

So far I've only modified the jersey, pants and socks, I won't do anything else because it's already been @paulov-t said that only jerseys work.

**Comment by TylerQuint** [comment]
> > @AndaleObe i applied a face mod using mod loader and compiled the game the miniface worked in game but the face mod didn't work but the default face appeared
> 
> So far I've only modified the jersey, pants and socks, I won't do anything else because it's already been @paulov-t said that only jerseys work.

Oh i hope we can mod more in future lets see

**Comment by AndaleObe** [comment]
> > > @AndaleObe i applied a face mod using mod loader and compiled the game the miniface worked in game but the face mod didn't work but the default face appeared
> > 
> > 
> > So far I've only modified the jersey, pants and socks, I won't do anything else because it's already been @paulov-t said that only jerseys work.
> 
> Oh i hope we can mod more in future lets see

Yes, me too, but I don't think @paulov-t  will do much anymore since he hasn't done anything or responded for a while now

**Comment by AndaleObe** [comment]
Do you have the legacy files for FC24 PS4 in FMT?

**Comment by TylerQuint** [comment]
> Do you have the legacy files for FC24 PS4 in FMT?

Yes

**Comment by AndaleObe** [comment]
I need your help

With this version FMT-24.0.8685.36478 the legacy files were loaded and displayed in NHL 23. Unfortunately, this version did not yet have texture export import support. With the latest version, the legacy files are no longer loaded or displayed. Does anyone know where I can change that? thank you for your help

**Comment by TylerQuint** [comment]
> I need your help
> 
> With this version FMT-24.0.8685.36478 the legacy files were loaded and displayed in NHL 23. Unfortunately, this version did not yet have texture export import support. With the latest version, the legacy files are no longer loaded or displayed. Does anyone know where I can change that? thank you for your help

Idk about that bro but its working fine for fc 24

**Comment by TylerQuint** [comment]
@AndaleObe this is how fc 24 modded kits looking
![IMG_20240112_221037_704](https://github.com/paulov-t/FrostbiteModdingTool/assets/152674326/2f1f2c44-4789-413f-a939-b94b5ae79a13)

**Comment by AndaleObe** [comment]
@paulov-t 
Please make it possible for the legacy files to be loaded again on NHL 23 PS4
