### ISSUE TITLE
star wars squadrons

### ISSUE THREAD

**Issue by zebbr** [paulov-t/FrostbiteModdingTool#29]
hi any chance you could make a profile for squadrons?

frosty tools suite 1.0.7 has a profile but it's read only so you can't mod...said they don't support games with EAC. not sure i see
the point of a profile for the game if they won't let us mod it.

the game on steam can be launched without EAC just fine if you're only interested in solo play. you just need to rename the launcher and created steam_appid.txt with the games id number in it and run the game from the other executable.

**Comment by zebbr** [comment]
hi,
it's quite simple really, on the steam version all you need to do is rename starwarssquadrons_launcher.exe like just add .bak on the end and then create a steam_appid.txt with 1222730 inside.
you can also uninstall EAC from the EasyAntiCheat folder. 
then all you do is run the game from starwarssquadrons.exe

don't run from steam as it will re-download the renamed file.

that's all there is to it.

**Comment by zebbr** [comment]
That's good news, btw i forgot to ask i noticed in the changes section you mention importing .fbmod files to the editor, does that mean for supported games users can edit / fix existing mods that have been abandoned by their creator?

i got a few old mods for battlefront II but only in fbmod format and they appear to be abandoned on nexus, no updates for 2 years. would love to sort them out. however i also noticed neither of the battlefront games are supported by your tool.

would you be willing to add support for the two battlefront games? currently the frosty editor doesn't allow fbmod files to be opened, i've tried adding the features as it's open source but my coding skills aren't great...

**Comment by zebbr** [comment]
i have yet to try your editor as i currently have no supported games, well apart from squadrons but i don't think it's working yet right? if you do happen to add support for the battlefront games that would be awesome. how's the stability of your editor? i still get random crashes on the frosty tool suite even though it's been going longer.

**Comment by zebbr** [comment]
i only asked as the fbmod import feature sounds handy, i know on frosty we can't open fbmod files as the coders say its to prevent mod theft. i still wish it had the option though as i like to tinker with stuff.

would you consider adding support for battlefront II ?

**Comment by zebbr** [comment]
finally got round to trying squadrons on your tool but it doesn't work. i built everything, have the net framework 7 installed, vs 2022 (latest build) i enabled the game to show in the launcher but when i try launching the editor it shows a big error dialog.
![FMT_error](https://user-images.githubusercontent.com/124896392/235642439-23774c45-dec9-4d20-9def-1efb43c2063f.png)

**Comment by zebbr** [comment]
i deleted my clone of the git and cloned it again and built the solution but it still crashes with the same error.

**Comment by zebbr** [comment]
just tried new build, still crashes on squadrons profile but with a different error now.

**Comment by zebbr** [comment]
ok, thanks.

**Comment by zebbr** [comment]
you seem to have made some progress with this game :)
however nothing appears to be editable though, whatever i try to open just shows three buttons and an empty window.
![sws](https://github.com/paulov-t/FrostbiteModdingTool/assets/124896392/6b22e064-5e8c-4cc6-96e1-3c39551c8c3e)

**Comment by zebbr** [comment]
hi, have you had a chance to look at this game yet? going through tough spot right now, glasses broke, few trips to dentist, lots of pain, need cheering up. would be very happy if i could finally mod this game. just tried latest build but still nothing in left hand pane. :(

**Comment by zebbr** [comment]
hi, any progress on this game yet?

**Comment by zebbr** [comment]
fair enough, personal life comes first as do more popular projects.

probable reason for not many using FMT is likely because everyone uses Frosty Tools Suite and are unaware of your tool. (unless you are into FIFA games)
shame the devs are so against modding games that have anti cheat, even games with almost dead mp community. SWS sucked for mp on release anyway.
the game has a profile on FTS but it's useless, even if you make it a full profile and run without EAC the game just ignores mods.
so i guess it wouldn't work on your tool either...

i managed to edit the initfs to disable TAA and lens flares so at least i've removed two things i dislike in the game.
i'll probably try 3dmigoto next to see if i can disable some hud elements.

**Comment by zebbr** [comment]
can now open some resources in the editor and edit things. game won't launch via the launcher though.

**Comment by zebbr** [comment]
hi,
are we any closer to mods working?

**Comment by zebbr** [comment]
> Hi @zebbr , I've now completed the read only aspect of the Star Wars Squadrons profile. Editing is the next step.

Thanks for the update, i look forward to each progression :)

**Comment by zebbr** [comment]
found some things that are not viewable in the editor, many things like visual environments are missing data that should be more drop down items.



![sfsdfsdf](https://github.com/paulov-t/FrostbiteModdingTool/assets/124896392/83b184e4-1032-470f-825b-6b6a82f4d68b)

**Comment by zebbr** [comment]
do you think modding might be ready by the end of the year or before ?

**Comment by zebbr** [comment]
i think it might be @ Game/UI/LoadingScreen/SplashScreenLoading

another worth trying would be @ FMV/FMV/Boot_Logos/

try disabling the videos, it's just like on battlefront, just remove the filename and change the numbers to zeros.

it was the first thing i tried on the frosty tool suite when i created a non read only profile...except nothing worked. even though the game was using the data path containing the mods.

**Comment by zebbr** [comment]
so no chance of modding at all then? i thought it might be the case.

**Comment by zebbr** [comment]
ok

**Comment by zebbr** [comment]
hi, any updates?

**Comment by zebbr** [comment]
i know you are working to support multiple games, just wondering, should i give up waiting on this? only keeping it installed as i was hoping mod support would be available at some point. can you say whether i should hang in there and wait or just move on?
was so hoping do some cool stuff like third person camera for all the ships as i'm not liking the cramped forced first person view but that seems like a pipe dream right now :(

**Comment by zebbr** [comment]
sorry for all the replies, just interested to know if mods will work or not ??

**Comment by zebbr** [comment]
i don't think this is ever going to happen so closing.

**Comment by Slarlac249** [comment]
been watching this, please don't give up on this, others are still interested.
